### ISSUE TITLE
error CS0246

### ISSUE THREAD

**Issue by GoogolHz** [willneedit/AltspaceUnityUploader#15]
I'm getting some errors loading a project after what was a seemingly successful install (no reported errors).  

Any hunches?
Library/PackageCache/org.willneedit.altspace_unity_uploader@ff6e22df9682-1630186399921/Editor/Common.cs(408,16): 
error CS0246: The type or namespace name 'Process' could not be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/org.willneedit.altspace_unity_uploader@ff6e22df9682-1630186399921/Editor/Common.cs(408,31): error CS0103: The name 'Process' does not exist in the current context

Library/PackageCache/org.willneedit.altspace_unity_uploader@ff6e22df9682-1630186399921/Editor/Common.cs(408,49): error CS0246: The type or namespace name 'ProcessStartInfo' could not be found (are you missing a using directive or an assembly reference?)

**Comment by willneedit** [comment]
The line numbers mentioned match the code in version v2.0.0. Did it take that long for someone to see that it was nonfunctional for Macs or is it just a recent development that this fix was needed?

NB: Should work, but cannot verify without a Mac.
