### ISSUE TITLE
Empty scene but getting error message saying {"errors":{"zip":["cannot contain scripts"]}}?

### ISSUE THREAD

**Issue by endasil** [willneedit/AltspaceUnityUploader#2]
I have no idea what AltspaceVR is looking at when generating that error but it sure isn't my scene since it is empty. Can be reproduced using this repository and loading level2 scene https://github.com/endasil/brokenupload

**Comment by willneedit** [comment]
https://discord.com/channels/493164419967221790/563407928929943582/805498462044291092

Looks like it's already resolved.

Maybe need to include a more fine grained version checking; just comparing to 2019.4(.x) doesn't cut it.
